extends Control

onready var Back = $Background
onready var Panel1 = $Panel
onready var Panel2 = $Panel2
onready var Panel3 = $Panel3
onready var Panel4 = $Panel4
onready var Panel5 = $Panel5
onready var Panel7 = $Panel7
onready var Panel8 = $Panel8
onready var Panel9 = $Panel9
onready var Panel10 = $Panel10
onready var Panel11 = $Panel11
onready var Panel12 = $Panel12
onready var Panel13 = $Panel13
onready var Panel14 = $Panel14
onready var ID1 = $NinePatchRect
onready var ID2 = $NinePatchRect2
onready var ID3 = $NinePatchRect3
onready var ID4 = $NinePatchRect4
onready var ID5 = $NinePatchRect5
onready var ID6 = $NinePatchRect6

var active_dialogue = 0 

func _on_WelcomeTimer_timeout():
	active_dialogue = active_dialogue+1

func _ready():
	Back.show()
	#print("Back.hidden", !Back.visible)
	Panel1.hide()
	#print("Panel1.hidden", !Panel1.visible)
	Panel2.hide()
	#print("Panel2.hidden", !Panel2.visible)
	Panel3.hide()
	#print("Panel3.hidden", !Panel3.visible)
	Panel4.hide()
	Panel5.hide()
	
	Panel8.hide()
	Panel9.hide()
	Panel10.hide()
	Panel11.hide()
	Panel12.hide()
	Panel13.hide()
	Panel14.hide()
	ID1.hide()
	#print("ID1.hidden", !ID1.visible)
	ID2.hide()
	#print("ID2.hidden", !ID2.visible)
	ID3.hide()
	#print("ID3.hidden", !ID3.visible)
	ID4.hide()
	ID5.hide()
	ID6.hide()
func _process(delta):
	if active_dialogue == 1:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect/AnimationPlayer2").play("fadeI")
	if active_dialogue == 3:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect2/AnimationPlayer2").play("fadeI")
	if active_dialogue == 5:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect3/AnimationPlayer2").play("fadeI")
	if active_dialogue == 7:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect4/AnimationPlayer2").play("fadeI")
	if active_dialogue == 9:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect5/AnimationPlayer2").play("fadeI")
	if active_dialogue == 11:
		get_node("/root/RootScene/Welcome/Control_1/NinePatchRect6/AnimationPlayer2").play("fadeI")
func _physics_process(delta):
	if active_dialogue == 1:
		Back.show()
		ID1.show()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 2:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.show()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 3:
		Back.show()
		ID1.hide()
		ID2.show()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 4:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.show()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 5:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.show()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 6:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.show()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 7: 
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.show()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()

	elif active_dialogue == 8:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.show()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 9:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.show()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 10:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.show()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 11:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.show()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 12:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.show()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 13:
		Back.show()
		ID1.show()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 14:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.show()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 15:
		Back.show()
		ID1.hide()
		ID2.show()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 16:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.show()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 17:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.show()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 18:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.show()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 19:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.show()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 20:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.show()
		Panel11.hide()
		Panel12.show()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 21:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.show()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 22:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.show()
		Panel14.hide()
	elif active_dialogue == 23:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.show()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
	elif active_dialogue == 24:
		Back.show()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.show()
		get_node("/root/RootScene/Welcome/AnimationPlayer").play("Fade")
	elif active_dialogue == 25:
		Back.hide()
		ID1.hide()
		ID2.hide()
		ID3.hide()
		ID4.hide()
		ID5.hide()
		ID6.hide()
		Panel1.hide()
		Panel2.hide()
		Panel3.hide()
		Panel4.hide()
		Panel5.hide()
		
		Panel8.hide()
		Panel9.hide()
		Panel10.hide()
		Panel11.hide()
		Panel12.hide()
		Panel13.hide()
		Panel14.hide()
